# Generated by Django 5.2.16 on 2026-07-19 03:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_organizationinvitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="API",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=170)),
                ("summary", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AI", "AI"),
                            ("PAYMENT", "Payment"),
                            ("WEATHER", "Weather"),
                            ("FINANCE", "Finance"),
                            ("HEALTHCARE", "Healthcare"),
                            ("DEVELOPER", "Developer Tools"),
                            ("UTILITY", "Utility"),
                        ],
                        default="UTILITY",
                        max_length=30,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("PRIVATE", "Private"),
                            ("UNLISTED", "Unlisted"),
                        ],
                        default="PRIVATE",
                        max_length=20,
                    ),
                ),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("DEPRECATED", "Deprecated"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("API_KEY", "API Key"),
                            ("JWT", "JWT"),
                            ("OAUTH2", "OAuth2"),
                        ],
                        default="API_KEY",
                        max_length=20,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("docs_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_apis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apis",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "apis",
                "ordering": ["-created_at"],
                "unique_together": {("organization", "slug")},
            },
        ),
    ]
