# Generated by Django 5.2.16 on 2026-07-19 05:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0002_api_deleted_at_api_deleted_by_apiversion"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("path", models.CharField(max_length=255)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=10,
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "authentication",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("API_KEY", "API Key"),
                            ("JWT", "JWT"),
                            ("OAUTH2", "OAuth2"),
                        ],
                        default="API_KEY",
                        max_length=20,
                    ),
                ),
                (
                    "rate_limit",
                    models.PositiveIntegerField(
                        default=1000, help_text="Requests per hour"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoints",
                        to="apis.apiversion",
                    ),
                ),
            ],
            options={
                "db_table": "api_endpoints",
                "ordering": ["path", "method"],
                "unique_together": {("version", "path", "method")},
            },
        ),
    ]
